### PR TITLE
✨ Adds Network UPS Tools add-on

### PR DESCRIPTION
**Pull request by dale3h**
# Proposed Changes

> This PR will add the [Network UPS Tools](https://github.com/hassio-addons/addon-nut) add-on to the stable repository.

## Related Issues

> N/A

### CODE REVIEW

**Comment by hmronline** [comment]
Please make it work, this add-on is really needed!!

**Comment by dale3h** [comment]
The NUT add-on appears to be ready for release. @frenck Please consider reopening this PR and merging.

**Comment by joshuata** [comment]
I am very interested in this add-on and would love to help if there is anything that needs to be done for the merge.

**Comment by hmronline** [comment]
This was not merged, why ?

**Comment by frenck** [comment]
because it is A) outdated, B) no updates from the original creator, C) reports of issues with it.

**Pull request closed without merging**
