### PR TITLE
Remove i386 for esphome addon

### PR DESCRIPTION
**Pull request by jesserockz**
# Proposed Changes

> (Describe the changes and rationale behind them)

Removes the i386 image of ESPHome

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

esphome/esphome-docker-base/issues/5

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by jesserockz** [comment]
@frenck The automated [commit](https://github.com/esphome/hassio/commit/e796cc81c170c39cf70b6614730c51c394349ca4) removed the `i386` arch, but the updater docker container [failed](https://github.com/esphome/hassio/runs/1109119791?check_suite_focus=true#step:3:237) to run the checks because it tried to find the `i386` image on docker hub. Unsure what else needs to be changed for this to work.

**Comment by glmnet** [comment]
Wow... was looking at the repository updater and of course, not an issue with the repository updater, somehow the release was made before the version bump commit, which included the removal of the arch from the config.json

According to the action [script](https://github.com/esphome/hassio/blob/master/.github/workflows/bump-version.yml), the bump is done then the release is done 

However the last commit is https://github.com/esphome/hassio/commit/e796cc81c170c39cf70b6614730c51c394349ca4 and the previous one is https://github.com/esphome/hassio/commit/4e415814244ed218ad7668afcbd7c943363cba3c and the v1.15 is tagging https://github.com/esphome/hassio/commit/4e415814244ed218ad7668afcbd7c943363cba3c for some reason

Are the actions steps allowed to run concurrently or something like that?

**Comment by jesserockz** [comment]
The `create-release` action uses the context sha by default and not the one that the previous step created.
esphome/hassio#15

**Comment by frenck** [comment]
Changing these files doesn't work.

**Comment by jesserockz** [comment]
> Changing these files doesn't work.

Yeah we figured out the issue. Thanks for the reply.

**Pull request closed without merging**
