### PR TITLE
Add EVCC addon to repository

### PR DESCRIPTION
**Pull request by andig**
# Proposed Changes

Add EVCC - PV-controlled EV Charge Controller - addon

## Related Issues

https://github.com/andig/evcc

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by andig** [comment]
Build errors seem unrelated to this PR.

**Comment by frenck** [comment]
This is not how this repository works. Furthermore, I'm not accepting new add-ons at this time, sorry.

**Comment by andig** [comment]
> The primary goal of this project is to provide you (as a Home Assistant user) with additional, high quality, add-ons that allow you to take your automated home to the next level.

So how *does* this repo work? And if you don‘t accept additions- why not say so on the frontpage? I‘ve wasted the time to do this PR ;)

**Comment by frenck** [comment]
Well, it does say contact me, not do a PR... so if you had read it, you didn't had to do this PR. Don't put that on me.

**Comment by andig** [comment]
I‘ve re-read the README and couldn‘t find it. Where does it say that?

**Comment by andig** [comment]
NVM. Found it. Would make sense to put the important notice on top rather than after the list of addons imho.

**Comment by frenck** [comment]
https://github.com/hassio-addons/repository#adding-a-new-add-on

image

**Comment by frenck** [comment]
LOL. yeah sure. The repository is aimed at end-users, not contributors. 

Stop making excuses and trying to blame it on me. You simply didn't read, nor invest time to look at the inner workings.

**Pull request closed without merging**
